<a href="https://colab.research.google.com/github/fafa20252025/fariba/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [99]:
import numpy as np
import pandas as pd


In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# **# Reading the dataset **

In [101]:
heart=pd.read_csv("heart.csv")

In [102]:
heart.head() #prints top 5 rows of data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1


In [103]:
heart.shape #rows and columns

(303, 14)

In [104]:
heart.dtypes #if there is an object data we need to encode it.

,0
age,int64
sex,int64
cp,int64
trestbps,int64
chol,int64
fbs,int64
restecg,int64
thalach,int64
exang,int64
oldpeak,float64


In [105]:
heart.isnull().sum()
# print the total number of missing values
#below means there are no missing values in any column below.

,0
age,0
sex,0
cp,0
trestbps,0
chol,0
fbs,0
restecg,0
thalach,0
exang,0
oldpeak,0


In [106]:
heart.duplicated().sum()
#print the total number of duplicate rows
#one duplicate row exists in the data


np.int64(1)

In [107]:
heart[heart.duplicated()]  #print duplicated row

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
164,38,1,2,138,175,0,1,173,0,0.0,2,4,2,1


In [108]:
heart.drop_duplicates(inplace=True)  #drops duplicate rows

In [109]:
Q1 = heart[['trestbps', 'chol', 'thalach', 'oldpeak']].quantile(0.25)
Q3 = heart[['trestbps', 'chol', 'thalach', 'oldpeak']].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter out the outliers
heart = heart[~((heart[['trestbps', 'chol', 'thalach', 'oldpeak']] < lower_bound) | (heart[['trestbps', 'chol', 'thalach', 'oldpeak']] > upper_bound)).any(axis=1)]

print(f"DataFrame shape after outlier removal: {heart.shape}")

DataFrame shape after outlier removal: (283, 14)


### Outlier Removal using IQR Method
To remove outliers, we use the Interquartile Range (IQR) method. This method identifies values that fall outside of 1.5 times the IQR from the first (Q1) and third (Q3) quartiles.

1.  **Calculate Q1 and Q3**: The 25th and 75th percentiles of the specified columns.
2.  **Calculate IQR**: The difference between Q3 and Q1.
3.  **Determine Bounds**: Any value below `Q1 - 1.5 * IQR` or above `Q3 + 1.5 * IQR` is considered an outlier.
4.  **Filter Data**: Rows containing outliers in the specified columns are removed from the DataFrame.

In [110]:
Q1 = heart[['trestbps', 'chol', 'thalach', 'oldpeak']].quantile(0.25)
Q3 = heart[['trestbps', 'chol', 'thalach', 'oldpeak']].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Filter out the outliers
heart = heart[~((heart[['trestbps', 'chol', 'thalach', 'oldpeak']] < lower_bound) | (heart[['trestbps', 'chol', 'thalach', 'oldpeak']] > upper_bound)).any(axis=1)]

print(f"DataFrame shape after outlier removal: {heart.shape}")

DataFrame shape after outlier removal: (283, 14)


# **###Machine Learning process**

In [111]:
# create variables (x and y)
x = heart.drop('target', axis=1)  #it means drop target from the columns and print every column
y = heart['target']

In [112]:
# split data into training and testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=100)


**##standardisation /scaling of the data**



In [113]:
scaler=StandardScaler()  #standardscaler is a class so we need to make an object of class (scaler).
x_train_scaled=scaler.fit_transform(x_train) # we take x_train data and store them in x_train_scaled variable
x_test_scaled=scaler.transform(x_test)

##applying Logistic Regression on the data

In [114]:
log_reg=LogisticRegression()  #LogisticRegression is a class and we make an object of it (log_reg)
log_reg.fit(x_train_scaled,y_train)

LogisticRegression()

In [115]:
log_reg.coef_

array([[-0.06305747, -0.85348714,  0.66449861, -0.2089306 , -0.17124147,
         0.19371637,  0.23259632,  0.36296555, -0.56523652, -0.60158511,
         0.39037737, -0.74269155, -0.59305471]])

In [116]:
log_reg.intercept_

array([0.36597716])

In [117]:
y_pred=log_reg.predict(x_test_scaled)

In [118]:
y_pred

array([0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1])

In [119]:
probs=log_reg.predict_proba(x_test_scaled) #it shows probability

In [120]:
probs  #first column is 0. second column is 1
# First row: first column is 0.93 probability of 0 and second column is 0.06 probability of 1
#second row : first column is 0.01 probability of 0 and second column is 0.98 probability of 1
#third row: first column is 0.78 probability of 0 and second column is 0.21 probability of 1
#fourth fow: first column is 0.79 probability of 0 and second column is 0.20 probability of 1

array([[0.9304504 , 0.0695496 ],
       [0.01052648, 0.98947352],
       [0.78723019, 0.21276981],
       [0.79943641, 0.20056359],
       [0.8770262 , 0.1229738 ],
       [0.15671351, 0.84328649],
       [0.00314297, 0.99685703],
       [0.15694544, 0.84305456],
       [0.93149389, 0.06850611],
       [0.87657766, 0.12342234],
       [0.75054801, 0.24945199],
       [0.04386246, 0.95613754],
       [0.58456553, 0.41543447],
       [0.98502858, 0.01497142],
       [0.03989986, 0.96010014],
       [0.06335111, 0.93664889],
       [0.38543076, 0.61456924],
       [0.0034803 , 0.9965197 ],
       [0.41579044, 0.58420956],
       [0.51989345, 0.48010655],
       [0.95789831, 0.04210169],
       [0.99478042, 0.00521958],
       [0.78039719, 0.21960281],
       [0.23434329, 0.76565671],
       [0.01350762, 0.98649238],
       [0.9699855 , 0.0300145 ],
       [0.80884837, 0.19115163],
       [0.92080199, 0.07919801],
       [0.68018137, 0.31981863],
       [0.90702971, 0.09297029],
       [0.

In [121]:
accuracy_score(y_test,y_pred)  #it compares y_test to y_pred

0.8245614035087719